//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2014/6/30 17:26:47
namespace UniCloud.Presentation.Service.FlightLog.FlightLog
{
    
    /// <summary>
    /// 架构中不存在 FlightLogData 的注释。
    /// </summary>
    public partial class FlightLogData : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 FlightLogData 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FlightLogData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "UniCloud.Application.FlightLogBC.DTO", "UniCloud.Presentation.Service.FlightLog.FlightLog");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("UniCloud.Presentation.Service.FlightLog.FlightLog", global::System.StringComparison.Ordinal))
            {
                return string.Concat("UniCloud.Application.FlightLogBC.DTO.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 FlightLogs 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FlightLogDTO> FlightLogs
        {
            get
            {
                if ((this._FlightLogs == null))
                {
                    this._FlightLogs = base.CreateQuery<FlightLogDTO>("FlightLogs");
                }
                return this._FlightLogs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FlightLogDTO> _FlightLogs;
        /// <summary>
        /// 架构中不存在 FlightLogs 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFlightLogs(FlightLogDTO flightLogDTO)
        {
            base.AddObject("FlightLogs", flightLogDTO);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"UniCloud.Application.FlightLogBC.DTO\" xmlns=\"http://schemas.microsoft" +
                ".com/ado/2007/05/edm\"><EntityType Name=\"FlightLogDTO\"><Key><PropertyRef Name=\"Id" +
                "\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"AcReg\" Type=\"Edm.String\" /><Property Name=\"MSN\" Type=\"Edm.String\" /><Property " +
                "Name=\"FlightDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"FlightH" +
                "ours\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property Name=\"TotalCycles\" Type=\"E" +
                "dm.Int32\" Nullable=\"false\" /></EntityType><ComplexType Name=\"AcFlightDataDTO\"><P" +
                "roperty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"RegNumber\"" +
                " Type=\"Edm.String\" /><Property Name=\"FlightDate\" Type=\"Edm.DateTime\" Nullable=\"f" +
                "alse\" /><Property Name=\"FlightHour\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Prope" +
                "rty Name=\"FlightCycle\" Type=\"Edm.Decimal\" Nullable=\"false\" /></ComplexType></Sch" +
                "ema><Schema Namespace=\"UniCloud.DistributedServices.FlightLog\" xmlns=\"http://sch" +
                "emas.microsoft.com/ado/2007/05/edm\"><EntityContainer Name=\"FlightLogData\" m:IsDe" +
                "faultEntityContainer=\"true\"><EntitySet Name=\"FlightLogs\" EntityType=\"UniCloud.Ap" +
                "plication.FlightLogBC.DTO.FlightLogDTO\" /><FunctionImport Name=\"QueryAcFlightDat" +
                "a\" ReturnType=\"Collection(UniCloud.Application.FlightLogBC.DTO.AcFlightDataDTO)\"" +
                " m:HttpMethod=\"GET\"><Parameter Name=\"regNumber\" Type=\"Edm.String\" /><Parameter N" +
                "ame=\"date\" Type=\"Edm.String\" /></FunctionImport></EntityContainer></Schema></edm" +
                "x:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.FlightLogBC.DTO.FlightLogDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FlightLogs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class FlightLogDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 FlightLogDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="flightDate">FlightDate 的初始值。</param>
        /// <param name="flightHours">FlightHours 的初始值。</param>
        /// <param name="totalCycles">TotalCycles 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FlightLogDTO CreateFlightLogDTO(int ID, global::System.DateTime flightDate, decimal flightHours, int totalCycles)
        {
            FlightLogDTO flightLogDTO = new FlightLogDTO();
            flightLogDTO.Id = ID;
            flightLogDTO.FlightDate = flightDate;
            flightLogDTO.FlightHours = flightHours;
            flightLogDTO.TotalCycles = totalCycles;
            return flightLogDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 AcReg 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AcReg
        {
            get
            {
                return this._AcReg;
            }
            set
            {
                this.OnAcRegChanging(value);
                this._AcReg = value;
                this.OnAcRegChanged();
                this.OnPropertyChanged("AcReg");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AcReg;
        partial void OnAcRegChanging(string value);
        partial void OnAcRegChanged();
        /// <summary>
        /// 架构中不存在属性 MSN 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MSN
        {
            get
            {
                return this._MSN;
            }
            set
            {
                this.OnMSNChanging(value);
                this._MSN = value;
                this.OnMSNChanged();
                this.OnPropertyChanged("MSN");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MSN;
        partial void OnMSNChanging(string value);
        partial void OnMSNChanged();
        /// <summary>
        /// 架构中不存在属性 FlightDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FlightDate
        {
            get
            {
                return this._FlightDate;
            }
            set
            {
                this.OnFlightDateChanging(value);
                this._FlightDate = value;
                this.OnFlightDateChanged();
                this.OnPropertyChanged("FlightDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FlightDate;
        partial void OnFlightDateChanging(global::System.DateTime value);
        partial void OnFlightDateChanged();
        /// <summary>
        /// 架构中不存在属性 FlightHours 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal FlightHours
        {
            get
            {
                return this._FlightHours;
            }
            set
            {
                this.OnFlightHoursChanging(value);
                this._FlightHours = value;
                this.OnFlightHoursChanged();
                this.OnPropertyChanged("FlightHours");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _FlightHours;
        partial void OnFlightHoursChanging(decimal value);
        partial void OnFlightHoursChanged();
        /// <summary>
        /// 架构中不存在属性 TotalCycles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TotalCycles
        {
            get
            {
                return this._TotalCycles;
            }
            set
            {
                this.OnTotalCyclesChanging(value);
                this._TotalCycles = value;
                this.OnTotalCyclesChanged();
                this.OnPropertyChanged("TotalCycles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TotalCycles;
        partial void OnTotalCyclesChanging(int value);
        partial void OnTotalCyclesChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ComplexType UniCloud.Application.FlightLogBC.DTO.AcFlightDataDTO 的注释。
    /// </summary>
    public partial class AcFlightDataDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AcFlightDataDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="flightDate">FlightDate 的初始值。</param>
        /// <param name="flightHour">FlightHour 的初始值。</param>
        /// <param name="flightCycle">FlightCycle 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AcFlightDataDTO CreateAcFlightDataDTO(int ID, global::System.DateTime flightDate, decimal flightHour, decimal flightCycle)
        {
            AcFlightDataDTO acFlightDataDTO = new AcFlightDataDTO();
            acFlightDataDTO.Id = ID;
            acFlightDataDTO.FlightDate = flightDate;
            acFlightDataDTO.FlightHour = flightHour;
            acFlightDataDTO.FlightCycle = flightCycle;
            return acFlightDataDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 RegNumber 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RegNumber
        {
            get
            {
                return this._RegNumber;
            }
            set
            {
                this.OnRegNumberChanging(value);
                this._RegNumber = value;
                this.OnRegNumberChanged();
                this.OnPropertyChanged("RegNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RegNumber;
        partial void OnRegNumberChanging(string value);
        partial void OnRegNumberChanged();
        /// <summary>
        /// 架构中不存在属性 FlightDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FlightDate
        {
            get
            {
                return this._FlightDate;
            }
            set
            {
                this.OnFlightDateChanging(value);
                this._FlightDate = value;
                this.OnFlightDateChanged();
                this.OnPropertyChanged("FlightDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FlightDate;
        partial void OnFlightDateChanging(global::System.DateTime value);
        partial void OnFlightDateChanged();
        /// <summary>
        /// 架构中不存在属性 FlightHour 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal FlightHour
        {
            get
            {
                return this._FlightHour;
            }
            set
            {
                this.OnFlightHourChanging(value);
                this._FlightHour = value;
                this.OnFlightHourChanged();
                this.OnPropertyChanged("FlightHour");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _FlightHour;
        partial void OnFlightHourChanging(decimal value);
        partial void OnFlightHourChanged();
        /// <summary>
        /// 架构中不存在属性 FlightCycle 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal FlightCycle
        {
            get
            {
                return this._FlightCycle;
            }
            set
            {
                this.OnFlightCycleChanging(value);
                this._FlightCycle = value;
                this.OnFlightCycleChanged();
                this.OnPropertyChanged("FlightCycle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _FlightCycle;
        partial void OnFlightCycleChanging(decimal value);
        partial void OnFlightCycleChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
