//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2014/2/7 14:19:48
namespace UniCloud.Presentation.Service.AircraftConfig.AircraftConfig
{
    
    /// <summary>
    /// 架构中不存在 AircraftConfigData 的注释。
    /// </summary>
    public partial class AircraftConfigData : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 AircraftConfigData 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AircraftConfigData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "UniCloud.Application.AircraftConfigBC.DTO", "UniCloud.Presentation.Service.AircraftConfig.AircraftConfig");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("UniCloud.Presentation.Service.AircraftConfig.AircraftConfig", global::System.StringComparison.Ordinal))
            {
                return string.Concat("UniCloud.Application.AircraftConfigBC.DTO.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 ActionCategories 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ActionCategoryDTO> ActionCategories
        {
            get
            {
                if ((this._ActionCategories == null))
                {
                    this._ActionCategories = base.CreateQuery<ActionCategoryDTO>("ActionCategories");
                }
                return this._ActionCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ActionCategoryDTO> _ActionCategories;
        /// <summary>
        /// 架构中不存在 AircraftSeries 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AircraftSeriesDTO> AircraftSeries
        {
            get
            {
                if ((this._AircraftSeries == null))
                {
                    this._AircraftSeries = base.CreateQuery<AircraftSeriesDTO>("AircraftSeries");
                }
                return this._AircraftSeries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AircraftSeriesDTO> _AircraftSeries;
        /// <summary>
        /// 架构中不存在 AircraftCategories 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AircraftCategoryDTO> AircraftCategories
        {
            get
            {
                if ((this._AircraftCategories == null))
                {
                    this._AircraftCategories = base.CreateQuery<AircraftCategoryDTO>("AircraftCategories");
                }
                return this._AircraftCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AircraftCategoryDTO> _AircraftCategories;
        /// <summary>
        /// 架构中不存在 AircraftTypes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AircraftTypeDTO> AircraftTypes
        {
            get
            {
                if ((this._AircraftTypes == null))
                {
                    this._AircraftTypes = base.CreateQuery<AircraftTypeDTO>("AircraftTypes");
                }
                return this._AircraftTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AircraftTypeDTO> _AircraftTypes;
        /// <summary>
        /// 架构中不存在 Manufacturers 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ManufacturerDTO> Manufacturers
        {
            get
            {
                if ((this._Manufacturers == null))
                {
                    this._Manufacturers = base.CreateQuery<ManufacturerDTO>("Manufacturers");
                }
                return this._Manufacturers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ManufacturerDTO> _Manufacturers;
        /// <summary>
        /// 架构中不存在 LicenseTypes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LicenseTypeDTO> LicenseTypes
        {
            get
            {
                if ((this._LicenseTypes == null))
                {
                    this._LicenseTypes = base.CreateQuery<LicenseTypeDTO>("LicenseTypes");
                }
                return this._LicenseTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LicenseTypeDTO> _LicenseTypes;
        /// <summary>
        /// 架构中不存在 Aircrafts 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AircraftDTO> Aircrafts
        {
            get
            {
                if ((this._Aircrafts == null))
                {
                    this._Aircrafts = base.CreateQuery<AircraftDTO>("Aircrafts");
                }
                return this._Aircrafts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AircraftDTO> _Aircrafts;
        /// <summary>
        /// 架构中不存在 ActionCategories 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToActionCategories(ActionCategoryDTO actionCategoryDTO)
        {
            base.AddObject("ActionCategories", actionCategoryDTO);
        }
        /// <summary>
        /// 架构中不存在 AircraftSeries 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAircraftSeries(AircraftSeriesDTO aircraftSeriesDTO)
        {
            base.AddObject("AircraftSeries", aircraftSeriesDTO);
        }
        /// <summary>
        /// 架构中不存在 AircraftCategories 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAircraftCategories(AircraftCategoryDTO aircraftCategoryDTO)
        {
            base.AddObject("AircraftCategories", aircraftCategoryDTO);
        }
        /// <summary>
        /// 架构中不存在 AircraftTypes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAircraftTypes(AircraftTypeDTO aircraftTypeDTO)
        {
            base.AddObject("AircraftTypes", aircraftTypeDTO);
        }
        /// <summary>
        /// 架构中不存在 Manufacturers 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToManufacturers(ManufacturerDTO manufacturerDTO)
        {
            base.AddObject("Manufacturers", manufacturerDTO);
        }
        /// <summary>
        /// 架构中不存在 LicenseTypes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLicenseTypes(LicenseTypeDTO licenseTypeDTO)
        {
            base.AddObject("LicenseTypes", licenseTypeDTO);
        }
        /// <summary>
        /// 架构中不存在 Aircrafts 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAircrafts(AircraftDTO aircraftDTO)
        {
            base.AddObject("Aircrafts", aircraftDTO);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"UniCloud.Application.AircraftConfigBC.DTO\" xmlns=\"http://schemas.micr" +
                "osoft.com/ado/2009/11/edm\"><EntityType Name=\"ActionCategoryDTO\"><Key><PropertyRe" +
                "f Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Prop" +
                "erty Name=\"ActionType\" Type=\"Edm.String\" /><Property Name=\"ActionName\" Type=\"Edm" +
                ".String\" /><Property Name=\"NeedRequest\" Type=\"Edm.Boolean\" Nullable=\"false\" /></" +
                "EntityType><EntityType Name=\"AircraftSeriesDTO\"><Key><PropertyRef Name=\"Id\" /></" +
                "Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Name\"" +
                " Type=\"Edm.String\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property " +
                "Name=\"ManufacturerName\" Type=\"Edm.String\" /><Property Name=\"ManufacturerId\" Type" +
                "=\"Edm.Guid\" Nullable=\"false\" /></EntityType><EntityType Name=\"AircraftCategoryDT" +
                "O\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nulla" +
                "ble=\"false\" /><Property Name=\"Category\" Type=\"Edm.String\" /><Property Name=\"Regi" +
                "onal\" Type=\"Edm.String\" /></EntityType><EntityType Name=\"AircraftTypeDTO\"><Key><" +
                "PropertyRef Name=\"AircraftTypeId\" /></Key><Property Name=\"AircraftTypeId\" Type=\"" +
                "Edm.Guid\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" /><Property" +
                " Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"AircraftCategoryId\" Type" +
                "=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"AircraftCategoryName\" Type=\"Edm.S" +
                "tring\" /><Property Name=\"AircraftSeriesId\" Type=\"Edm.Guid\" Nullable=\"false\" /><P" +
                "roperty Name=\"AircraftSeriesName\" Type=\"Edm.String\" /><Property Name=\"Manufactur" +
                "erId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"ManufacturerName\" Type=" +
                "\"Edm.String\" /></EntityType><EntityType Name=\"ManufacturerDTO\"><Key><PropertyRef" +
                " Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Prope" +
                "rty Name=\"CnName\" Type=\"Edm.String\" /><Property Name=\"EnName\" Type=\"Edm.String\" " +
                "/><Property Name=\"CnShortName\" Type=\"Edm.String\" /><Property Name=\"EnShortName\" " +
                "Type=\"Edm.String\" /><Property Name=\"Note\" Type=\"Edm.String\" /><Property Name=\"Ty" +
                "pe\" Type=\"Edm.Int32\" Nullable=\"false\" /></EntityType><EntityType Name=\"LicenseTy" +
                "peDTO\"><Key><PropertyRef Name=\"LicenseTypeId\" /></Key><Property Name=\"LicenseTyp" +
                "eId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\"" +
                " /><Property Name=\"HasFile\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name" +
                "=\"Description\" Type=\"Edm.String\" /></EntityType><EntityType Name=\"AircraftDTO\"><" +
                "Key><PropertyRef Name=\"AircraftId\" /></Key><Property Name=\"AircraftId\" Type=\"Edm" +
                ".Guid\" Nullable=\"false\" /><Property Name=\"RegNumber\" Type=\"Edm.String\" /><Proper" +
                "ty Name=\"SerialNumber\" Type=\"Edm.String\" /><Property Name=\"IsOperation\" Type=\"Ed" +
                "m.Boolean\" Nullable=\"false\" /><Property Name=\"CreateDate\" Type=\"Edm.DateTime\" Nu" +
                "llable=\"false\" /><Property Name=\"FactoryDate\" Type=\"Edm.DateTime\" /><Property Na" +
                "me=\"ImportDate\" Type=\"Edm.DateTime\" /><Property Name=\"ExportDate\" Type=\"Edm.Date" +
                "Time\" /><Property Name=\"SeatingCapacity\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pr" +
                "operty Name=\"CarryingCapacity\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property N" +
                "ame=\"SupplierName\" Type=\"Edm.String\" /><Property Name=\"AircraftTypeName\" Type=\"E" +
                "dm.String\" /><Property Name=\"AirlinesName\" Type=\"Edm.String\" /><Property Name=\"I" +
                "mportCategoryName\" Type=\"Edm.String\" /><Property Name=\"ManufacturerName\" Type=\"E" +
                "dm.String\" /><Property Name=\"Regional\" Type=\"Edm.String\" /><Property Name=\"Aircr" +
                "aftLicenses\" Type=\"Collection(UniCloud.Application.AircraftConfigBC.DTO.Aircraft" +
                "LicenseDTO)\" Nullable=\"false\" /><Property Name=\"SupplierId\" Type=\"Edm.Int32\" /><" +
                "Property Name=\"AircraftTypeId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name" +
                "=\"AirlinesId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"ImportCategoryI" +
                "d\" Type=\"Edm.Guid\" Nullable=\"false\" /></EntityType><ComplexType Name=\"AircraftLi" +
                "censeDTO\"><Property Name=\"AircraftLicenseId\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
                "><Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Description\" Type=\"Ed" +
                "m.String\" /><Property Name=\"IssuedUnit\" Type=\"Edm.String\" /><Property Name=\"Issu" +
                "edDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"ValidMonths\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ExpireDate\" Type=\"Edm.DateTime\" " +
                "Nullable=\"false\" /><Property Name=\"State\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "roperty Name=\"FileContent\" Type=\"Edm.Binary\" /><Property Name=\"FileName\" Type=\"E" +
                "dm.String\" /><Property Name=\"AircraftId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Pro" +
                "perty Name=\"LicenseTypeId\" Type=\"Edm.Int32\" Nullable=\"false\" /></ComplexType></S" +
                "chema><Schema Namespace=\"UniCloud.DistributedServices.AircraftConfig\" xmlns=\"htt" +
                "p://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"AircraftConfig" +
                "Data\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"ActionCategories\" Entit" +
                "yType=\"UniCloud.Application.AircraftConfigBC.DTO.ActionCategoryDTO\" /><EntitySet" +
                " Name=\"AircraftSeries\" EntityType=\"UniCloud.Application.AircraftConfigBC.DTO.Air" +
                "craftSeriesDTO\" /><EntitySet Name=\"AircraftCategories\" EntityType=\"UniCloud.Appl" +
                "ication.AircraftConfigBC.DTO.AircraftCategoryDTO\" /><EntitySet Name=\"AircraftTyp" +
                "es\" EntityType=\"UniCloud.Application.AircraftConfigBC.DTO.AircraftTypeDTO\" /><En" +
                "titySet Name=\"Manufacturers\" EntityType=\"UniCloud.Application.AircraftConfigBC.D" +
                "TO.ManufacturerDTO\" /><EntitySet Name=\"LicenseTypes\" EntityType=\"UniCloud.Applic" +
                "ation.AircraftConfigBC.DTO.LicenseTypeDTO\" /><EntitySet Name=\"Aircrafts\" EntityT" +
                "ype=\"UniCloud.Application.AircraftConfigBC.DTO.AircraftDTO\" /></EntityContainer>" +
                "</Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.ActionCategoryDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ActionCategories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ActionCategoryDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 ActionCategoryDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="needRequest">NeedRequest 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ActionCategoryDTO CreateActionCategoryDTO(global::System.Guid ID, bool needRequest)
        {
            ActionCategoryDTO actionCategoryDTO = new ActionCategoryDTO();
            actionCategoryDTO.Id = ID;
            actionCategoryDTO.NeedRequest = needRequest;
            return actionCategoryDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 ActionType 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionType
        {
            get
            {
                return this._ActionType;
            }
            set
            {
                this.OnActionTypeChanging(value);
                this._ActionType = value;
                this.OnActionTypeChanged();
                this.OnPropertyChanged("ActionType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionType;
        partial void OnActionTypeChanging(string value);
        partial void OnActionTypeChanged();
        /// <summary>
        /// 架构中不存在属性 ActionName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionName
        {
            get
            {
                return this._ActionName;
            }
            set
            {
                this.OnActionNameChanging(value);
                this._ActionName = value;
                this.OnActionNameChanged();
                this.OnPropertyChanged("ActionName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionName;
        partial void OnActionNameChanging(string value);
        partial void OnActionNameChanged();
        /// <summary>
        /// 架构中不存在属性 NeedRequest 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool NeedRequest
        {
            get
            {
                return this._NeedRequest;
            }
            set
            {
                this.OnNeedRequestChanging(value);
                this._NeedRequest = value;
                this.OnNeedRequestChanged();
                this.OnPropertyChanged("NeedRequest");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _NeedRequest;
        partial void OnNeedRequestChanging(bool value);
        partial void OnNeedRequestChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.AircraftSeriesDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AircraftSeries")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AircraftSeriesDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AircraftSeriesDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="manufacturerId">ManufacturerId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AircraftSeriesDTO CreateAircraftSeriesDTO(global::System.Guid ID, global::System.Guid manufacturerId)
        {
            AircraftSeriesDTO aircraftSeriesDTO = new AircraftSeriesDTO();
            aircraftSeriesDTO.Id = ID;
            aircraftSeriesDTO.ManufacturerId = manufacturerId;
            return aircraftSeriesDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 ManufacturerName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ManufacturerName
        {
            get
            {
                return this._ManufacturerName;
            }
            set
            {
                this.OnManufacturerNameChanging(value);
                this._ManufacturerName = value;
                this.OnManufacturerNameChanged();
                this.OnPropertyChanged("ManufacturerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ManufacturerName;
        partial void OnManufacturerNameChanging(string value);
        partial void OnManufacturerNameChanged();
        /// <summary>
        /// 架构中不存在属性 ManufacturerId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ManufacturerId
        {
            get
            {
                return this._ManufacturerId;
            }
            set
            {
                this.OnManufacturerIdChanging(value);
                this._ManufacturerId = value;
                this.OnManufacturerIdChanged();
                this.OnPropertyChanged("ManufacturerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ManufacturerId;
        partial void OnManufacturerIdChanging(global::System.Guid value);
        partial void OnManufacturerIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.AircraftCategoryDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AircraftCategories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AircraftCategoryDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AircraftCategoryDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AircraftCategoryDTO CreateAircraftCategoryDTO(global::System.Guid ID)
        {
            AircraftCategoryDTO aircraftCategoryDTO = new AircraftCategoryDTO();
            aircraftCategoryDTO.Id = ID;
            return aircraftCategoryDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Category 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// 架构中不存在属性 Regional 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Regional
        {
            get
            {
                return this._Regional;
            }
            set
            {
                this.OnRegionalChanging(value);
                this._Regional = value;
                this.OnRegionalChanged();
                this.OnPropertyChanged("Regional");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Regional;
        partial void OnRegionalChanging(string value);
        partial void OnRegionalChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.AircraftTypeDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// AircraftTypeId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AircraftTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AircraftTypeId")]
    public partial class AircraftTypeDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AircraftTypeDTO 对象。
        /// </summary>
        /// <param name="aircraftTypeId">AircraftTypeId 的初始值。</param>
        /// <param name="aircraftCategoryId">AircraftCategoryId 的初始值。</param>
        /// <param name="aircraftSeriesId">AircraftSeriesId 的初始值。</param>
        /// <param name="manufacturerId">ManufacturerId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AircraftTypeDTO CreateAircraftTypeDTO(global::System.Guid aircraftTypeId, global::System.Guid aircraftCategoryId, global::System.Guid aircraftSeriesId, global::System.Guid manufacturerId)
        {
            AircraftTypeDTO aircraftTypeDTO = new AircraftTypeDTO();
            aircraftTypeDTO.AircraftTypeId = aircraftTypeId;
            aircraftTypeDTO.AircraftCategoryId = aircraftCategoryId;
            aircraftTypeDTO.AircraftSeriesId = aircraftSeriesId;
            aircraftTypeDTO.ManufacturerId = manufacturerId;
            return aircraftTypeDTO;
        }
        /// <summary>
        /// 架构中不存在属性 AircraftTypeId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AircraftTypeId
        {
            get
            {
                return this._AircraftTypeId;
            }
            set
            {
                this.OnAircraftTypeIdChanging(value);
                this._AircraftTypeId = value;
                this.OnAircraftTypeIdChanged();
                this.OnPropertyChanged("AircraftTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AircraftTypeId;
        partial void OnAircraftTypeIdChanging(global::System.Guid value);
        partial void OnAircraftTypeIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftCategoryId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AircraftCategoryId
        {
            get
            {
                return this._AircraftCategoryId;
            }
            set
            {
                this.OnAircraftCategoryIdChanging(value);
                this._AircraftCategoryId = value;
                this.OnAircraftCategoryIdChanged();
                this.OnPropertyChanged("AircraftCategoryId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AircraftCategoryId;
        partial void OnAircraftCategoryIdChanging(global::System.Guid value);
        partial void OnAircraftCategoryIdChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftCategoryName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AircraftCategoryName
        {
            get
            {
                return this._AircraftCategoryName;
            }
            set
            {
                this.OnAircraftCategoryNameChanging(value);
                this._AircraftCategoryName = value;
                this.OnAircraftCategoryNameChanged();
                this.OnPropertyChanged("AircraftCategoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AircraftCategoryName;
        partial void OnAircraftCategoryNameChanging(string value);
        partial void OnAircraftCategoryNameChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftSeriesId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AircraftSeriesId
        {
            get
            {
                return this._AircraftSeriesId;
            }
            set
            {
                this.OnAircraftSeriesIdChanging(value);
                this._AircraftSeriesId = value;
                this.OnAircraftSeriesIdChanged();
                this.OnPropertyChanged("AircraftSeriesId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AircraftSeriesId;
        partial void OnAircraftSeriesIdChanging(global::System.Guid value);
        partial void OnAircraftSeriesIdChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftSeriesName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AircraftSeriesName
        {
            get
            {
                return this._AircraftSeriesName;
            }
            set
            {
                this.OnAircraftSeriesNameChanging(value);
                this._AircraftSeriesName = value;
                this.OnAircraftSeriesNameChanged();
                this.OnPropertyChanged("AircraftSeriesName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AircraftSeriesName;
        partial void OnAircraftSeriesNameChanging(string value);
        partial void OnAircraftSeriesNameChanged();
        /// <summary>
        /// 架构中不存在属性 ManufacturerId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ManufacturerId
        {
            get
            {
                return this._ManufacturerId;
            }
            set
            {
                this.OnManufacturerIdChanging(value);
                this._ManufacturerId = value;
                this.OnManufacturerIdChanged();
                this.OnPropertyChanged("ManufacturerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ManufacturerId;
        partial void OnManufacturerIdChanging(global::System.Guid value);
        partial void OnManufacturerIdChanged();
        /// <summary>
        /// 架构中不存在属性 ManufacturerName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ManufacturerName
        {
            get
            {
                return this._ManufacturerName;
            }
            set
            {
                this.OnManufacturerNameChanging(value);
                this._ManufacturerName = value;
                this.OnManufacturerNameChanged();
                this.OnPropertyChanged("ManufacturerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ManufacturerName;
        partial void OnManufacturerNameChanging(string value);
        partial void OnManufacturerNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.ManufacturerDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Manufacturers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ManufacturerDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 ManufacturerDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="type">Type 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ManufacturerDTO CreateManufacturerDTO(global::System.Guid ID, int type)
        {
            ManufacturerDTO manufacturerDTO = new ManufacturerDTO();
            manufacturerDTO.Id = ID;
            manufacturerDTO.Type = type;
            return manufacturerDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 CnName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CnName
        {
            get
            {
                return this._CnName;
            }
            set
            {
                this.OnCnNameChanging(value);
                this._CnName = value;
                this.OnCnNameChanged();
                this.OnPropertyChanged("CnName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CnName;
        partial void OnCnNameChanging(string value);
        partial void OnCnNameChanged();
        /// <summary>
        /// 架构中不存在属性 EnName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EnName
        {
            get
            {
                return this._EnName;
            }
            set
            {
                this.OnEnNameChanging(value);
                this._EnName = value;
                this.OnEnNameChanged();
                this.OnPropertyChanged("EnName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EnName;
        partial void OnEnNameChanging(string value);
        partial void OnEnNameChanged();
        /// <summary>
        /// 架构中不存在属性 CnShortName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CnShortName
        {
            get
            {
                return this._CnShortName;
            }
            set
            {
                this.OnCnShortNameChanging(value);
                this._CnShortName = value;
                this.OnCnShortNameChanged();
                this.OnPropertyChanged("CnShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CnShortName;
        partial void OnCnShortNameChanging(string value);
        partial void OnCnShortNameChanged();
        /// <summary>
        /// 架构中不存在属性 EnShortName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EnShortName
        {
            get
            {
                return this._EnShortName;
            }
            set
            {
                this.OnEnShortNameChanging(value);
                this._EnShortName = value;
                this.OnEnShortNameChanged();
                this.OnPropertyChanged("EnShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EnShortName;
        partial void OnEnShortNameChanging(string value);
        partial void OnEnShortNameChanged();
        /// <summary>
        /// 架构中不存在属性 Note 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// 架构中不存在属性 Type 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.LicenseTypeDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// LicenseTypeId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("LicenseTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("LicenseTypeId")]
    public partial class LicenseTypeDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 LicenseTypeDTO 对象。
        /// </summary>
        /// <param name="licenseTypeId">LicenseTypeId 的初始值。</param>
        /// <param name="hasFile">HasFile 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LicenseTypeDTO CreateLicenseTypeDTO(int licenseTypeId, bool hasFile)
        {
            LicenseTypeDTO licenseTypeDTO = new LicenseTypeDTO();
            licenseTypeDTO.LicenseTypeId = licenseTypeId;
            licenseTypeDTO.HasFile = hasFile;
            return licenseTypeDTO;
        }
        /// <summary>
        /// 架构中不存在属性 LicenseTypeId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LicenseTypeId
        {
            get
            {
                return this._LicenseTypeId;
            }
            set
            {
                this.OnLicenseTypeIdChanging(value);
                this._LicenseTypeId = value;
                this.OnLicenseTypeIdChanged();
                this.OnPropertyChanged("LicenseTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LicenseTypeId;
        partial void OnLicenseTypeIdChanging(int value);
        partial void OnLicenseTypeIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 HasFile 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool HasFile
        {
            get
            {
                return this._HasFile;
            }
            set
            {
                this.OnHasFileChanging(value);
                this._HasFile = value;
                this.OnHasFileChanged();
                this.OnPropertyChanged("HasFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _HasFile;
        partial void OnHasFileChanging(bool value);
        partial void OnHasFileChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ComplexType UniCloud.Application.AircraftConfigBC.DTO.AircraftLicenseDTO 的注释。
    /// </summary>
    public partial class AircraftLicenseDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AircraftLicenseDTO 对象。
        /// </summary>
        /// <param name="aircraftLicenseId">AircraftLicenseId 的初始值。</param>
        /// <param name="issuedDate">IssuedDate 的初始值。</param>
        /// <param name="validMonths">ValidMonths 的初始值。</param>
        /// <param name="expireDate">ExpireDate 的初始值。</param>
        /// <param name="state">State 的初始值。</param>
        /// <param name="aircraftId">AircraftId 的初始值。</param>
        /// <param name="licenseTypeId">LicenseTypeId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AircraftLicenseDTO CreateAircraftLicenseDTO(int aircraftLicenseId, global::System.DateTime issuedDate, int validMonths, global::System.DateTime expireDate, int state, global::System.Guid aircraftId, int licenseTypeId)
        {
            AircraftLicenseDTO aircraftLicenseDTO = new AircraftLicenseDTO();
            aircraftLicenseDTO.AircraftLicenseId = aircraftLicenseId;
            aircraftLicenseDTO.IssuedDate = issuedDate;
            aircraftLicenseDTO.ValidMonths = validMonths;
            aircraftLicenseDTO.ExpireDate = expireDate;
            aircraftLicenseDTO.State = state;
            aircraftLicenseDTO.AircraftId = aircraftId;
            aircraftLicenseDTO.LicenseTypeId = licenseTypeId;
            return aircraftLicenseDTO;
        }
        /// <summary>
        /// 架构中不存在属性 AircraftLicenseId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AircraftLicenseId
        {
            get
            {
                return this._AircraftLicenseId;
            }
            set
            {
                this.OnAircraftLicenseIdChanging(value);
                this._AircraftLicenseId = value;
                this.OnAircraftLicenseIdChanged();
                this.OnPropertyChanged("AircraftLicenseId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AircraftLicenseId;
        partial void OnAircraftLicenseIdChanging(int value);
        partial void OnAircraftLicenseIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 IssuedUnit 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IssuedUnit
        {
            get
            {
                return this._IssuedUnit;
            }
            set
            {
                this.OnIssuedUnitChanging(value);
                this._IssuedUnit = value;
                this.OnIssuedUnitChanged();
                this.OnPropertyChanged("IssuedUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IssuedUnit;
        partial void OnIssuedUnitChanging(string value);
        partial void OnIssuedUnitChanged();
        /// <summary>
        /// 架构中不存在属性 IssuedDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime IssuedDate
        {
            get
            {
                return this._IssuedDate;
            }
            set
            {
                this.OnIssuedDateChanging(value);
                this._IssuedDate = value;
                this.OnIssuedDateChanged();
                this.OnPropertyChanged("IssuedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _IssuedDate;
        partial void OnIssuedDateChanging(global::System.DateTime value);
        partial void OnIssuedDateChanged();
        /// <summary>
        /// 架构中不存在属性 ValidMonths 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ValidMonths
        {
            get
            {
                return this._ValidMonths;
            }
            set
            {
                this.OnValidMonthsChanging(value);
                this._ValidMonths = value;
                this.OnValidMonthsChanged();
                this.OnPropertyChanged("ValidMonths");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ValidMonths;
        partial void OnValidMonthsChanging(int value);
        partial void OnValidMonthsChanged();
        /// <summary>
        /// 架构中不存在属性 ExpireDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ExpireDate
        {
            get
            {
                return this._ExpireDate;
            }
            set
            {
                this.OnExpireDateChanging(value);
                this._ExpireDate = value;
                this.OnExpireDateChanged();
                this.OnPropertyChanged("ExpireDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ExpireDate;
        partial void OnExpireDateChanging(global::System.DateTime value);
        partial void OnExpireDateChanged();
        /// <summary>
        /// 架构中不存在属性 State 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _State;
        partial void OnStateChanging(int value);
        partial void OnStateChanged();
        /// <summary>
        /// 架构中不存在属性 FileContent 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] FileContent
        {
            get
            {
                if ((this._FileContent != null))
                {
                    return ((byte[])(this._FileContent.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnFileContentChanging(value);
                this._FileContent = value;
                this.OnFileContentChanged();
                this.OnPropertyChanged("FileContent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _FileContent;
        partial void OnFileContentChanging(byte[] value);
        partial void OnFileContentChanged();
        /// <summary>
        /// 架构中不存在属性 FileName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this._FileName = value;
                this.OnFileNameChanged();
                this.OnPropertyChanged("FileName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AircraftId
        {
            get
            {
                return this._AircraftId;
            }
            set
            {
                this.OnAircraftIdChanging(value);
                this._AircraftId = value;
                this.OnAircraftIdChanged();
                this.OnPropertyChanged("AircraftId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AircraftId;
        partial void OnAircraftIdChanging(global::System.Guid value);
        partial void OnAircraftIdChanged();
        /// <summary>
        /// 架构中不存在属性 LicenseTypeId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LicenseTypeId
        {
            get
            {
                return this._LicenseTypeId;
            }
            set
            {
                this.OnLicenseTypeIdChanging(value);
                this._LicenseTypeId = value;
                this.OnLicenseTypeIdChanged();
                this.OnPropertyChanged("LicenseTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LicenseTypeId;
        partial void OnLicenseTypeIdChanging(int value);
        partial void OnLicenseTypeIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.AircraftConfigBC.DTO.AircraftDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// AircraftId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Aircrafts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AircraftId")]
    public partial class AircraftDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AircraftDTO 对象。
        /// </summary>
        /// <param name="aircraftId">AircraftId 的初始值。</param>
        /// <param name="isOperation">IsOperation 的初始值。</param>
        /// <param name="createDate">CreateDate 的初始值。</param>
        /// <param name="seatingCapacity">SeatingCapacity 的初始值。</param>
        /// <param name="carryingCapacity">CarryingCapacity 的初始值。</param>
        /// <param name="aircraftLicenses">AircraftLicenses 的初始值。</param>
        /// <param name="aircraftTypeId">AircraftTypeId 的初始值。</param>
        /// <param name="airlinesId">AirlinesId 的初始值。</param>
        /// <param name="importCategoryId">ImportCategoryId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AircraftDTO CreateAircraftDTO(global::System.Guid aircraftId, bool isOperation, global::System.DateTime createDate, int seatingCapacity, decimal carryingCapacity, global::System.Collections.ObjectModel.ObservableCollection<AircraftLicenseDTO> aircraftLicenses, global::System.Guid aircraftTypeId, global::System.Guid airlinesId, global::System.Guid importCategoryId)
        {
            AircraftDTO aircraftDTO = new AircraftDTO();
            aircraftDTO.AircraftId = aircraftId;
            aircraftDTO.IsOperation = isOperation;
            aircraftDTO.CreateDate = createDate;
            aircraftDTO.SeatingCapacity = seatingCapacity;
            aircraftDTO.CarryingCapacity = carryingCapacity;
            if ((aircraftLicenses == null))
            {
                throw new global::System.ArgumentNullException("aircraftLicenses");
            }
            aircraftDTO.AircraftLicenses = aircraftLicenses;
            aircraftDTO.AircraftTypeId = aircraftTypeId;
            aircraftDTO.AirlinesId = airlinesId;
            aircraftDTO.ImportCategoryId = importCategoryId;
            return aircraftDTO;
        }
        /// <summary>
        /// 架构中不存在属性 AircraftId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AircraftId
        {
            get
            {
                return this._AircraftId;
            }
            set
            {
                this.OnAircraftIdChanging(value);
                this._AircraftId = value;
                this.OnAircraftIdChanged();
                this.OnPropertyChanged("AircraftId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AircraftId;
        partial void OnAircraftIdChanging(global::System.Guid value);
        partial void OnAircraftIdChanged();
        /// <summary>
        /// 架构中不存在属性 RegNumber 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RegNumber
        {
            get
            {
                return this._RegNumber;
            }
            set
            {
                this.OnRegNumberChanging(value);
                this._RegNumber = value;
                this.OnRegNumberChanged();
                this.OnPropertyChanged("RegNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RegNumber;
        partial void OnRegNumberChanging(string value);
        partial void OnRegNumberChanged();
        /// <summary>
        /// 架构中不存在属性 SerialNumber 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this.OnSerialNumberChanging(value);
                this._SerialNumber = value;
                this.OnSerialNumberChanged();
                this.OnPropertyChanged("SerialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerialNumber;
        partial void OnSerialNumberChanging(string value);
        partial void OnSerialNumberChanged();
        /// <summary>
        /// 架构中不存在属性 IsOperation 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsOperation
        {
            get
            {
                return this._IsOperation;
            }
            set
            {
                this.OnIsOperationChanging(value);
                this._IsOperation = value;
                this.OnIsOperationChanged();
                this.OnPropertyChanged("IsOperation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsOperation;
        partial void OnIsOperationChanging(bool value);
        partial void OnIsOperationChanged();
        /// <summary>
        /// 架构中不存在属性 CreateDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
                this.OnPropertyChanged("CreateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// 架构中不存在属性 FactoryDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> FactoryDate
        {
            get
            {
                return this._FactoryDate;
            }
            set
            {
                this.OnFactoryDateChanging(value);
                this._FactoryDate = value;
                this.OnFactoryDateChanged();
                this.OnPropertyChanged("FactoryDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _FactoryDate;
        partial void OnFactoryDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnFactoryDateChanged();
        /// <summary>
        /// 架构中不存在属性 ImportDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this.OnImportDateChanging(value);
                this._ImportDate = value;
                this.OnImportDateChanged();
                this.OnPropertyChanged("ImportDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ImportDate;
        partial void OnImportDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnImportDateChanged();
        /// <summary>
        /// 架构中不存在属性 ExportDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ExportDate
        {
            get
            {
                return this._ExportDate;
            }
            set
            {
                this.OnExportDateChanging(value);
                this._ExportDate = value;
                this.OnExportDateChanged();
                this.OnPropertyChanged("ExportDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ExportDate;
        partial void OnExportDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnExportDateChanged();
        /// <summary>
        /// 架构中不存在属性 SeatingCapacity 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SeatingCapacity
        {
            get
            {
                return this._SeatingCapacity;
            }
            set
            {
                this.OnSeatingCapacityChanging(value);
                this._SeatingCapacity = value;
                this.OnSeatingCapacityChanged();
                this.OnPropertyChanged("SeatingCapacity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SeatingCapacity;
        partial void OnSeatingCapacityChanging(int value);
        partial void OnSeatingCapacityChanged();
        /// <summary>
        /// 架构中不存在属性 CarryingCapacity 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal CarryingCapacity
        {
            get
            {
                return this._CarryingCapacity;
            }
            set
            {
                this.OnCarryingCapacityChanging(value);
                this._CarryingCapacity = value;
                this.OnCarryingCapacityChanged();
                this.OnPropertyChanged("CarryingCapacity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _CarryingCapacity;
        partial void OnCarryingCapacityChanging(decimal value);
        partial void OnCarryingCapacityChanged();
        /// <summary>
        /// 架构中不存在属性 SupplierName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SupplierName
        {
            get
            {
                return this._SupplierName;
            }
            set
            {
                this.OnSupplierNameChanging(value);
                this._SupplierName = value;
                this.OnSupplierNameChanged();
                this.OnPropertyChanged("SupplierName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SupplierName;
        partial void OnSupplierNameChanging(string value);
        partial void OnSupplierNameChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftTypeName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AircraftTypeName
        {
            get
            {
                return this._AircraftTypeName;
            }
            set
            {
                this.OnAircraftTypeNameChanging(value);
                this._AircraftTypeName = value;
                this.OnAircraftTypeNameChanged();
                this.OnPropertyChanged("AircraftTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AircraftTypeName;
        partial void OnAircraftTypeNameChanging(string value);
        partial void OnAircraftTypeNameChanged();
        /// <summary>
        /// 架构中不存在属性 AirlinesName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AirlinesName
        {
            get
            {
                return this._AirlinesName;
            }
            set
            {
                this.OnAirlinesNameChanging(value);
                this._AirlinesName = value;
                this.OnAirlinesNameChanged();
                this.OnPropertyChanged("AirlinesName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AirlinesName;
        partial void OnAirlinesNameChanging(string value);
        partial void OnAirlinesNameChanged();
        /// <summary>
        /// 架构中不存在属性 ImportCategoryName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ImportCategoryName
        {
            get
            {
                return this._ImportCategoryName;
            }
            set
            {
                this.OnImportCategoryNameChanging(value);
                this._ImportCategoryName = value;
                this.OnImportCategoryNameChanged();
                this.OnPropertyChanged("ImportCategoryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ImportCategoryName;
        partial void OnImportCategoryNameChanging(string value);
        partial void OnImportCategoryNameChanged();
        /// <summary>
        /// 架构中不存在属性 ManufacturerName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ManufacturerName
        {
            get
            {
                return this._ManufacturerName;
            }
            set
            {
                this.OnManufacturerNameChanging(value);
                this._ManufacturerName = value;
                this.OnManufacturerNameChanged();
                this.OnPropertyChanged("ManufacturerName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ManufacturerName;
        partial void OnManufacturerNameChanging(string value);
        partial void OnManufacturerNameChanged();
        /// <summary>
        /// 架构中不存在属性 Regional 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Regional
        {
            get
            {
                return this._Regional;
            }
            set
            {
                this.OnRegionalChanging(value);
                this._Regional = value;
                this.OnRegionalChanged();
                this.OnPropertyChanged("Regional");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Regional;
        partial void OnRegionalChanging(string value);
        partial void OnRegionalChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftLicenses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<AircraftLicenseDTO> AircraftLicenses
        {
            get
            {
                return this._AircraftLicenses;
            }
            set
            {
                this.OnAircraftLicensesChanging(value);
                this._AircraftLicenses = value;
                this.OnAircraftLicensesChanged();
                this.OnPropertyChanged("AircraftLicenses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<AircraftLicenseDTO> _AircraftLicenses = new global::System.Collections.ObjectModel.ObservableCollection<AircraftLicenseDTO>();
        partial void OnAircraftLicensesChanging(global::System.Collections.ObjectModel.ObservableCollection<AircraftLicenseDTO> value);
        partial void OnAircraftLicensesChanged();
        /// <summary>
        /// 架构中不存在属性 SupplierId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> SupplierId
        {
            get
            {
                return this._SupplierId;
            }
            set
            {
                this.OnSupplierIdChanging(value);
                this._SupplierId = value;
                this.OnSupplierIdChanged();
                this.OnPropertyChanged("SupplierId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _SupplierId;
        partial void OnSupplierIdChanging(global::System.Nullable<int> value);
        partial void OnSupplierIdChanged();
        /// <summary>
        /// 架构中不存在属性 AircraftTypeId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AircraftTypeId
        {
            get
            {
                return this._AircraftTypeId;
            }
            set
            {
                this.OnAircraftTypeIdChanging(value);
                this._AircraftTypeId = value;
                this.OnAircraftTypeIdChanged();
                this.OnPropertyChanged("AircraftTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AircraftTypeId;
        partial void OnAircraftTypeIdChanging(global::System.Guid value);
        partial void OnAircraftTypeIdChanged();
        /// <summary>
        /// 架构中不存在属性 AirlinesId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid AirlinesId
        {
            get
            {
                return this._AirlinesId;
            }
            set
            {
                this.OnAirlinesIdChanging(value);
                this._AirlinesId = value;
                this.OnAirlinesIdChanged();
                this.OnPropertyChanged("AirlinesId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _AirlinesId;
        partial void OnAirlinesIdChanging(global::System.Guid value);
        partial void OnAirlinesIdChanged();
        /// <summary>
        /// 架构中不存在属性 ImportCategoryId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ImportCategoryId
        {
            get
            {
                return this._ImportCategoryId;
            }
            set
            {
                this.OnImportCategoryIdChanging(value);
                this._ImportCategoryId = value;
                this.OnImportCategoryIdChanged();
                this.OnPropertyChanged("ImportCategoryId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ImportCategoryId;
        partial void OnImportCategoryIdChanging(global::System.Guid value);
        partial void OnImportCategoryIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
