//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Domain.PurchaseBC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniCloud.Domain.PurchaseBC.Resources.DisplayInfo", typeof(DisplayInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 签约 的本地化字符串。
        /// </summary>
        public static string BFEStatus_Contract {
            get {
                return ResourceManager.GetString("BFEStatus_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交付飞机制造商 的本地化字符串。
        /// </summary>
        public static string BFEStatus_Delivery {
            get {
                return ResourceManager.GetString("BFEStatus_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造 的本地化字符串。
        /// </summary>
        public static string BFEStatus_Manufacture {
            get {
                return ResourceManager.GetString("BFEStatus_Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审核 的本地化字符串。
        /// </summary>
        public static string OrderStatus_Checked {
            get {
                return ResourceManager.GetString("OrderStatus_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待审核 的本地化字符串。
        /// </summary>
        public static string OrderStatus_Checking {
            get {
                return ResourceManager.GetString("OrderStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿 的本地化字符串。
        /// </summary>
        public static string OrderStatus_Draft {
            get {
                return ResourceManager.GetString("OrderStatus_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string ReceptionStatus_Complete {
            get {
                return ResourceManager.GetString("ReceptionStatus_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行中 的本地化字符串。
        /// </summary>
        public static string ReceptionStatus_InProgress {
            get {
                return ResourceManager.GetString("ReceptionStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string ReceptionStatus_Repeal {
            get {
                return ResourceManager.GetString("ReceptionStatus_Repeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string ReceptionStatus_Start {
            get {
                return ResourceManager.GetString("ReceptionStatus_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国外 的本地化字符串。
        /// </summary>
        public static string SupplierType_Foreign {
            get {
                return ResourceManager.GetString("SupplierType_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国内 的本地化字符串。
        /// </summary>
        public static string SupplierType_Inland {
            get {
                return ResourceManager.GetString("SupplierType_Inland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string TradeStatus_Complete {
            get {
                return ResourceManager.GetString("TradeStatus_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行中 的本地化字符串。
        /// </summary>
        public static string TradeStatus_InProgress {
            get {
                return ResourceManager.GetString("TradeStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string TradeStatus_Repeal {
            get {
                return ResourceManager.GetString("TradeStatus_Repeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string TradeStatus_Start {
            get {
                return ResourceManager.GetString("TradeStatus_Start", resourceCulture);
            }
        }
    }
}
