//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2014/6/20 22:18:33
namespace UniCloud.Presentation.Service.BaseManagement.BaseManagement
{
    
    /// <summary>
    /// 架构中不存在 BaseManagementData 的注释。
    /// </summary>
    public partial class BaseManagementData : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 BaseManagementData 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public BaseManagementData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "UniCloud.Application.BaseManagementBC.DTO", "UniCloud.Presentation.Service.BaseManagement.BaseManagement");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("UniCloud.Presentation.Service.BaseManagement.BaseManagement", global::System.StringComparison.Ordinal))
            {
                return string.Concat("UniCloud.Application.BaseManagementBC.DTO.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserDTO> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<UserDTO>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserDTO> _Users;
        /// <summary>
        /// 架构中不存在 Organizations 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrganizationDTO> Organizations
        {
            get
            {
                if ((this._Organizations == null))
                {
                    this._Organizations = base.CreateQuery<OrganizationDTO>("Organizations");
                }
                return this._Organizations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrganizationDTO> _Organizations;
        /// <summary>
        /// 架构中不存在 FunctionItems 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FunctionItemDTO> FunctionItems
        {
            get
            {
                if ((this._FunctionItems == null))
                {
                    this._FunctionItems = base.CreateQuery<FunctionItemDTO>("FunctionItems");
                }
                return this._FunctionItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FunctionItemDTO> _FunctionItems;
        /// <summary>
        /// 架构中不存在 Roles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RoleDTO> Roles
        {
            get
            {
                if ((this._Roles == null))
                {
                    this._Roles = base.CreateQuery<RoleDTO>("Roles");
                }
                return this._Roles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RoleDTO> _Roles;
        /// <summary>
        /// 架构中不存在 BusinessLicenses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BusinessLicenseDTO> BusinessLicenses
        {
            get
            {
                if ((this._BusinessLicenses == null))
                {
                    this._BusinessLicenses = base.CreateQuery<BusinessLicenseDTO>("BusinessLicenses");
                }
                return this._BusinessLicenses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BusinessLicenseDTO> _BusinessLicenses;
        /// <summary>
        /// 架构中不存在 AircraftCabinTypes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AircraftCabinTypeDTO> AircraftCabinTypes
        {
            get
            {
                if ((this._AircraftCabinTypes == null))
                {
                    this._AircraftCabinTypes = base.CreateQuery<AircraftCabinTypeDTO>("AircraftCabinTypes");
                }
                return this._AircraftCabinTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AircraftCabinTypeDTO> _AircraftCabinTypes;
        /// <summary>
        /// 架构中不存在 XmlSettings 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<XmlSettingDTO> XmlSettings
        {
            get
            {
                if ((this._XmlSettings == null))
                {
                    this._XmlSettings = base.CreateQuery<XmlSettingDTO>("XmlSettings");
                }
                return this._XmlSettings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<XmlSettingDTO> _XmlSettings;
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(UserDTO userDTO)
        {
            base.AddObject("Users", userDTO);
        }
        /// <summary>
        /// 架构中不存在 Organizations 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrganizations(OrganizationDTO organizationDTO)
        {
            base.AddObject("Organizations", organizationDTO);
        }
        /// <summary>
        /// 架构中不存在 FunctionItems 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFunctionItems(FunctionItemDTO functionItemDTO)
        {
            base.AddObject("FunctionItems", functionItemDTO);
        }
        /// <summary>
        /// 架构中不存在 Roles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRoles(RoleDTO roleDTO)
        {
            base.AddObject("Roles", roleDTO);
        }
        /// <summary>
        /// 架构中不存在 BusinessLicenses 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBusinessLicenses(BusinessLicenseDTO businessLicenseDTO)
        {
            base.AddObject("BusinessLicenses", businessLicenseDTO);
        }
        /// <summary>
        /// 架构中不存在 AircraftCabinTypes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAircraftCabinTypes(AircraftCabinTypeDTO aircraftCabinTypeDTO)
        {
            base.AddObject("AircraftCabinTypes", aircraftCabinTypeDTO);
        }
        /// <summary>
        /// 架构中不存在 XmlSettings 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToXmlSettings(XmlSettingDTO xmlSettingDTO)
        {
            base.AddObject("XmlSettings", xmlSettingDTO);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"UniCloud.Application.BaseManagementBC.DTO\" xmlns=\"http://schemas.micr" +
                "osoft.com/ado/2009/11/edm\"><EntityType Name=\"UserDTO\"><Key><PropertyRef Name=\"Id" +
                "\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"EmployeeCode\" Type=\"Edm.String\" /><Property Name=\"OrganizationNo\" Type=\"Edm.St" +
                "ring\" /><Property Name=\"DisplayName\" Type=\"Edm.String\" /><Property Name=\"Passwor" +
                "d\" Type=\"Edm.String\" /><Property Name=\"Email\" Type=\"Edm.String\" /><Property Name" +
                "=\"Mobile\" Type=\"Edm.String\" /><Property Name=\"Description\" Type=\"Edm.String\" /><" +
                "Property Name=\"CreateDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name" +
                "=\"OrganizationName\" Type=\"Edm.String\" /><Property Name=\"UserRoles\" Type=\"Collect" +
                "ion(UniCloud.Application.BaseManagementBC.DTO.UserRoleDTO)\" Nullable=\"false\" /><" +
                "/EntityType><ComplexType Name=\"UserRoleDTO\"><Property Name=\"Id\" Type=\"Edm.Int32\"" +
                " Nullable=\"false\" /><Property Name=\"UserId\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<Property Name=\"RoleId\" Type=\"Edm.Int32\" Nullable=\"false\" /></ComplexType><Entit" +
                "yType Name=\"OrganizationDTO\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=" +
                "\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Code\" Type=\"Edm.String\"" +
                " /><Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"LastUpdateTime\" Typ" +
                "e=\"Edm.DateTime\" /><Property Name=\"IsValid\" Type=\"Edm.Boolean\" Nullable=\"false\" " +
                "/><Property Name=\"ParentCode\" Type=\"Edm.Int32\" /><Property Name=\"Sort\" Type=\"Edm" +
                ".Int32\" Nullable=\"false\" /><Property Name=\"CreateDate\" Type=\"Edm.DateTime\" Nulla" +
                "ble=\"false\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"O" +
                "rganizationRoles\" Type=\"Collection(UniCloud.Application.BaseManagementBC.DTO.Org" +
                "anizationRoleDTO)\" Nullable=\"false\" /></EntityType><ComplexType Name=\"Organizati" +
                "onRoleDTO\"><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Nam" +
                "e=\"OrganizationId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"RoleId\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" /></ComplexType><EntityType Name=\"FunctionItemD" +
                "TO\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nul" +
                "lable=\"false\" /><Property Name=\"ParentItemId\" Type=\"Edm.Int32\" /><Property Name=" +
                "\"IsLeaf\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Sort\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" /><Property Nam" +
                "e=\"Description\" Type=\"Edm.String\" /><Property Name=\"NaviUrl\" Type=\"Edm.String\" /" +
                "><Property Name=\"IsValid\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"" +
                "CreateDate\" Type=\"Edm.DateTime\" /><Property Name=\"ImageUrl\" Type=\"Edm.String\" />" +
                "<Property Name=\"IsButton\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"" +
                "IsChecked\" Type=\"Edm.Boolean\" Nullable=\"false\" /><NavigationProperty Name=\"SubFu" +
                "nctionItems\" Relationship=\"UniCloud.Application.BaseManagementBC.DTO.FunctionIte" +
                "mDTO_SubFunctionItems\" ToRole=\"SubFunctionItems\" FromRole=\"FunctionItemDTO\" /></" +
                "EntityType><EntityType Name=\"RoleDTO\"><Key><PropertyRef Name=\"Id\" /></Key><Prope" +
                "rty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Ed" +
                "m.String\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Cre" +
                "ateDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"RoleFunctions\" T" +
                "ype=\"Collection(UniCloud.Application.BaseManagementBC.DTO.RoleFunctionDTO)\" Null" +
                "able=\"false\" /></EntityType><ComplexType Name=\"RoleFunctionDTO\"><Property Name=\"" +
                "Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"FunctionItemId\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /><Property Name=\"RoleId\" Type=\"Edm.Int32\" Nullable=\"f" +
                "alse\" /></ComplexType><EntityType Name=\"BusinessLicenseDTO\"><Key><PropertyRef Na" +
                "me=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Description\" Type=\"Edm.String\"" +
                " /><Property Name=\"IssuedUnit\" Type=\"Edm.String\" /><Property Name=\"IssuedDate\" T" +
                "ype=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"ValidMonths\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"ExpireDate\" Type=\"Edm.DateTime\" Nullable=" +
                "\"false\" /><Property Name=\"State\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property N" +
                "ame=\"FileContent\" Type=\"Edm.Binary\" /><Property Name=\"FileName\" Type=\"Edm.String" +
                "\" /></EntityType><EntityType Name=\"AircraftCabinTypeDTO\"><Key><PropertyRef Name=" +
                "\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property N" +
                "ame=\"Name\" Type=\"Edm.String\" /><Property Name=\"Note\" Type=\"Edm.String\" /></Entit" +
                "yType><EntityType Name=\"XmlSettingDTO\"><Key><PropertyRef Name=\"XmlSettingId\" /><" +
                "/Key><Property Name=\"XmlSettingId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property " +
                "Name=\"SettingType\" Type=\"Edm.String\" /><Property Name=\"SettingContent\" Type=\"Edm" +
                ".String\" /></EntityType><Association Name=\"FunctionItemDTO_SubFunctionItems\"><En" +
                "d Type=\"UniCloud.Application.BaseManagementBC.DTO.FunctionItemDTO\" Role=\"SubFunc" +
                "tionItems\" Multiplicity=\"*\" /><End Type=\"UniCloud.Application.BaseManagementBC.D" +
                "TO.FunctionItemDTO\" Role=\"FunctionItemDTO\" Multiplicity=\"*\" /></Association></Sc" +
                "hema><Schema Namespace=\"UniCloud.DistributedServices.BaseManagement\" xmlns=\"http" +
                "://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"BaseManagementD" +
                "ata\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Users\" EntityType=\"UniCl" +
                "oud.Application.BaseManagementBC.DTO.UserDTO\" /><EntitySet Name=\"Organizations\" " +
                "EntityType=\"UniCloud.Application.BaseManagementBC.DTO.OrganizationDTO\" /><Entity" +
                "Set Name=\"FunctionItems\" EntityType=\"UniCloud.Application.BaseManagementBC.DTO.F" +
                "unctionItemDTO\" /><EntitySet Name=\"Roles\" EntityType=\"UniCloud.Application.BaseM" +
                "anagementBC.DTO.RoleDTO\" /><EntitySet Name=\"BusinessLicenses\" EntityType=\"UniClo" +
                "ud.Application.BaseManagementBC.DTO.BusinessLicenseDTO\" /><EntitySet Name=\"Aircr" +
                "aftCabinTypes\" EntityType=\"UniCloud.Application.BaseManagementBC.DTO.AircraftCab" +
                "inTypeDTO\" /><EntitySet Name=\"XmlSettings\" EntityType=\"UniCloud.Application.Base" +
                "ManagementBC.DTO.XmlSettingDTO\" /><FunctionImport Name=\"GetFunctionItemsWithHier" +
                "archy\" ReturnType=\"Collection(UniCloud.Application.BaseManagementBC.DTO.Function" +
                "ItemDTO)\" EntitySet=\"FunctionItems\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"G" +
                "etFunctionItemsByUser\" ReturnType=\"Collection(UniCloud.Application.BaseManagemen" +
                "tBC.DTO.FunctionItemDTO)\" EntitySet=\"FunctionItems\" m:HttpMethod=\"GET\"><Paramete" +
                "r Name=\"userId\" Type=\"Edm.String\" /></FunctionImport><AssociationSet Name=\"Funct" +
                "ionItemDTO_SubFunctionItems\" Association=\"UniCloud.Application.BaseManagementBC." +
                "DTO.FunctionItemDTO_SubFunctionItems\"><End Role=\"FunctionItemDTO\" EntitySet=\"Fun" +
                "ctionItems\" /><End Role=\"SubFunctionItems\" EntitySet=\"FunctionItems\" /></Associa" +
                "tionSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ComplexType UniCloud.Application.BaseManagementBC.DTO.UserRoleDTO 的注释。
    /// </summary>
    public partial class UserRoleDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 UserRoleDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="userId">UserId 的初始值。</param>
        /// <param name="roleId">RoleId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserRoleDTO CreateUserRoleDTO(int ID, int userId, int roleId)
        {
            UserRoleDTO userRoleDTO = new UserRoleDTO();
            userRoleDTO.Id = ID;
            userRoleDTO.UserId = userId;
            userRoleDTO.RoleId = roleId;
            return userRoleDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 UserId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// 架构中不存在属性 RoleId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this.OnRoleIdChanging(value);
                this._RoleId = value;
                this.OnRoleIdChanged();
                this.OnPropertyChanged("RoleId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RoleId;
        partial void OnRoleIdChanging(int value);
        partial void OnRoleIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.UserDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UserDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 UserDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="createDate">CreateDate 的初始值。</param>
        /// <param name="userRoles">UserRoles 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserDTO CreateUserDTO(int ID, global::System.DateTime createDate, global::System.Collections.ObjectModel.ObservableCollection<UserRoleDTO> userRoles)
        {
            UserDTO userDTO = new UserDTO();
            userDTO.Id = ID;
            userDTO.CreateDate = createDate;
            if ((userRoles == null))
            {
                throw new global::System.ArgumentNullException("userRoles");
            }
            userDTO.UserRoles = userRoles;
            return userDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 EmployeeCode 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmployeeCode
        {
            get
            {
                return this._EmployeeCode;
            }
            set
            {
                this.OnEmployeeCodeChanging(value);
                this._EmployeeCode = value;
                this.OnEmployeeCodeChanged();
                this.OnPropertyChanged("EmployeeCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmployeeCode;
        partial void OnEmployeeCodeChanging(string value);
        partial void OnEmployeeCodeChanged();
        /// <summary>
        /// 架构中不存在属性 OrganizationNo 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OrganizationNo
        {
            get
            {
                return this._OrganizationNo;
            }
            set
            {
                this.OnOrganizationNoChanging(value);
                this._OrganizationNo = value;
                this.OnOrganizationNoChanged();
                this.OnPropertyChanged("OrganizationNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OrganizationNo;
        partial void OnOrganizationNoChanging(string value);
        partial void OnOrganizationNoChanged();
        /// <summary>
        /// 架构中不存在属性 DisplayName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("DisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// 架构中不存在属性 Password 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// 架构中不存在属性 Email 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// 架构中不存在属性 Mobile 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Mobile
        {
            get
            {
                return this._Mobile;
            }
            set
            {
                this.OnMobileChanging(value);
                this._Mobile = value;
                this.OnMobileChanged();
                this.OnPropertyChanged("Mobile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Mobile;
        partial void OnMobileChanging(string value);
        partial void OnMobileChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 CreateDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
                this.OnPropertyChanged("CreateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// 架构中不存在属性 OrganizationName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OrganizationName
        {
            get
            {
                return this._OrganizationName;
            }
            set
            {
                this.OnOrganizationNameChanging(value);
                this._OrganizationName = value;
                this.OnOrganizationNameChanged();
                this.OnPropertyChanged("OrganizationName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OrganizationName;
        partial void OnOrganizationNameChanging(string value);
        partial void OnOrganizationNameChanged();
        /// <summary>
        /// 架构中不存在属性 UserRoles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<UserRoleDTO> UserRoles
        {
            get
            {
                return this._UserRoles;
            }
            set
            {
                this.OnUserRolesChanging(value);
                this._UserRoles = value;
                this.OnUserRolesChanged();
                this.OnPropertyChanged("UserRoles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<UserRoleDTO> _UserRoles = new global::System.Collections.ObjectModel.ObservableCollection<UserRoleDTO>();
        partial void OnUserRolesChanging(global::System.Collections.ObjectModel.ObservableCollection<UserRoleDTO> value);
        partial void OnUserRolesChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ComplexType UniCloud.Application.BaseManagementBC.DTO.OrganizationRoleDTO 的注释。
    /// </summary>
    public partial class OrganizationRoleDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 OrganizationRoleDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="organizationId">OrganizationId 的初始值。</param>
        /// <param name="roleId">RoleId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OrganizationRoleDTO CreateOrganizationRoleDTO(int ID, int organizationId, int roleId)
        {
            OrganizationRoleDTO organizationRoleDTO = new OrganizationRoleDTO();
            organizationRoleDTO.Id = ID;
            organizationRoleDTO.OrganizationId = organizationId;
            organizationRoleDTO.RoleId = roleId;
            return organizationRoleDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 OrganizationId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OrganizationId
        {
            get
            {
                return this._OrganizationId;
            }
            set
            {
                this.OnOrganizationIdChanging(value);
                this._OrganizationId = value;
                this.OnOrganizationIdChanged();
                this.OnPropertyChanged("OrganizationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OrganizationId;
        partial void OnOrganizationIdChanging(int value);
        partial void OnOrganizationIdChanged();
        /// <summary>
        /// 架构中不存在属性 RoleId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this.OnRoleIdChanging(value);
                this._RoleId = value;
                this.OnRoleIdChanged();
                this.OnPropertyChanged("RoleId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RoleId;
        partial void OnRoleIdChanging(int value);
        partial void OnRoleIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.OrganizationDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Organizations")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class OrganizationDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 OrganizationDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="isValid">IsValid 的初始值。</param>
        /// <param name="sort">Sort 的初始值。</param>
        /// <param name="createDate">CreateDate 的初始值。</param>
        /// <param name="organizationRoles">OrganizationRoles 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OrganizationDTO CreateOrganizationDTO(int ID, bool isValid, int sort, global::System.DateTime createDate, global::System.Collections.ObjectModel.ObservableCollection<OrganizationRoleDTO> organizationRoles)
        {
            OrganizationDTO organizationDTO = new OrganizationDTO();
            organizationDTO.Id = ID;
            organizationDTO.IsValid = isValid;
            organizationDTO.Sort = sort;
            organizationDTO.CreateDate = createDate;
            if ((organizationRoles == null))
            {
                throw new global::System.ArgumentNullException("organizationRoles");
            }
            organizationDTO.OrganizationRoles = organizationRoles;
            return organizationDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Code 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 LastUpdateTime 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastUpdateTime
        {
            get
            {
                return this._LastUpdateTime;
            }
            set
            {
                this.OnLastUpdateTimeChanging(value);
                this._LastUpdateTime = value;
                this.OnLastUpdateTimeChanged();
                this.OnPropertyChanged("LastUpdateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastUpdateTime;
        partial void OnLastUpdateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastUpdateTimeChanged();
        /// <summary>
        /// 架构中不存在属性 IsValid 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsValid
        {
            get
            {
                return this._IsValid;
            }
            set
            {
                this.OnIsValidChanging(value);
                this._IsValid = value;
                this.OnIsValidChanged();
                this.OnPropertyChanged("IsValid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsValid;
        partial void OnIsValidChanging(bool value);
        partial void OnIsValidChanged();
        /// <summary>
        /// 架构中不存在属性 ParentCode 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ParentCode
        {
            get
            {
                return this._ParentCode;
            }
            set
            {
                this.OnParentCodeChanging(value);
                this._ParentCode = value;
                this.OnParentCodeChanged();
                this.OnPropertyChanged("ParentCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ParentCode;
        partial void OnParentCodeChanging(global::System.Nullable<int> value);
        partial void OnParentCodeChanged();
        /// <summary>
        /// 架构中不存在属性 Sort 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Sort
        {
            get
            {
                return this._Sort;
            }
            set
            {
                this.OnSortChanging(value);
                this._Sort = value;
                this.OnSortChanged();
                this.OnPropertyChanged("Sort");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Sort;
        partial void OnSortChanging(int value);
        partial void OnSortChanged();
        /// <summary>
        /// 架构中不存在属性 CreateDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
                this.OnPropertyChanged("CreateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 OrganizationRoles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<OrganizationRoleDTO> OrganizationRoles
        {
            get
            {
                return this._OrganizationRoles;
            }
            set
            {
                this.OnOrganizationRolesChanging(value);
                this._OrganizationRoles = value;
                this.OnOrganizationRolesChanged();
                this.OnPropertyChanged("OrganizationRoles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<OrganizationRoleDTO> _OrganizationRoles = new global::System.Collections.ObjectModel.ObservableCollection<OrganizationRoleDTO>();
        partial void OnOrganizationRolesChanging(global::System.Collections.ObjectModel.ObservableCollection<OrganizationRoleDTO> value);
        partial void OnOrganizationRolesChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.FunctionItemDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FunctionItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class FunctionItemDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 FunctionItemDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="isLeaf">IsLeaf 的初始值。</param>
        /// <param name="sort">Sort 的初始值。</param>
        /// <param name="isValid">IsValid 的初始值。</param>
        /// <param name="isButton">IsButton 的初始值。</param>
        /// <param name="isChecked">IsChecked 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FunctionItemDTO CreateFunctionItemDTO(int ID, bool isLeaf, int sort, bool isValid, bool isButton, bool isChecked)
        {
            FunctionItemDTO functionItemDTO = new FunctionItemDTO();
            functionItemDTO.Id = ID;
            functionItemDTO.IsLeaf = isLeaf;
            functionItemDTO.Sort = sort;
            functionItemDTO.IsValid = isValid;
            functionItemDTO.IsButton = isButton;
            functionItemDTO.IsChecked = isChecked;
            return functionItemDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 ParentItemId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ParentItemId
        {
            get
            {
                return this._ParentItemId;
            }
            set
            {
                this.OnParentItemIdChanging(value);
                this._ParentItemId = value;
                this.OnParentItemIdChanged();
                this.OnPropertyChanged("ParentItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ParentItemId;
        partial void OnParentItemIdChanging(global::System.Nullable<int> value);
        partial void OnParentItemIdChanged();
        /// <summary>
        /// 架构中不存在属性 IsLeaf 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsLeaf
        {
            get
            {
                return this._IsLeaf;
            }
            set
            {
                this.OnIsLeafChanging(value);
                this._IsLeaf = value;
                this.OnIsLeafChanged();
                this.OnPropertyChanged("IsLeaf");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsLeaf;
        partial void OnIsLeafChanging(bool value);
        partial void OnIsLeafChanged();
        /// <summary>
        /// 架构中不存在属性 Sort 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Sort
        {
            get
            {
                return this._Sort;
            }
            set
            {
                this.OnSortChanging(value);
                this._Sort = value;
                this.OnSortChanged();
                this.OnPropertyChanged("Sort");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Sort;
        partial void OnSortChanging(int value);
        partial void OnSortChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 NaviUrl 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NaviUrl
        {
            get
            {
                return this._NaviUrl;
            }
            set
            {
                this.OnNaviUrlChanging(value);
                this._NaviUrl = value;
                this.OnNaviUrlChanged();
                this.OnPropertyChanged("NaviUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NaviUrl;
        partial void OnNaviUrlChanging(string value);
        partial void OnNaviUrlChanged();
        /// <summary>
        /// 架构中不存在属性 IsValid 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsValid
        {
            get
            {
                return this._IsValid;
            }
            set
            {
                this.OnIsValidChanging(value);
                this._IsValid = value;
                this.OnIsValidChanged();
                this.OnPropertyChanged("IsValid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsValid;
        partial void OnIsValidChanging(bool value);
        partial void OnIsValidChanged();
        /// <summary>
        /// 架构中不存在属性 CreateDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
                this.OnPropertyChanged("CreateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// 架构中不存在属性 ImageUrl 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ImageUrl
        {
            get
            {
                return this._ImageUrl;
            }
            set
            {
                this.OnImageUrlChanging(value);
                this._ImageUrl = value;
                this.OnImageUrlChanged();
                this.OnPropertyChanged("ImageUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ImageUrl;
        partial void OnImageUrlChanging(string value);
        partial void OnImageUrlChanged();
        /// <summary>
        /// 架构中不存在属性 IsButton 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsButton
        {
            get
            {
                return this._IsButton;
            }
            set
            {
                this.OnIsButtonChanging(value);
                this._IsButton = value;
                this.OnIsButtonChanged();
                this.OnPropertyChanged("IsButton");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsButton;
        partial void OnIsButtonChanging(bool value);
        partial void OnIsButtonChanged();
        /// <summary>
        /// 架构中不存在属性 IsChecked 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsChecked
        {
            get
            {
                return this._IsChecked;
            }
            set
            {
                this.OnIsCheckedChanging(value);
                this._IsChecked = value;
                this.OnIsCheckedChanged();
                this.OnPropertyChanged("IsChecked");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsChecked;
        partial void OnIsCheckedChanging(bool value);
        partial void OnIsCheckedChanged();
        /// <summary>
        /// 架构中不存在 SubFunctionItems 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<FunctionItemDTO> SubFunctionItems
        {
            get
            {
                return this._SubFunctionItems;
            }
            set
            {
                this._SubFunctionItems = value;
                this.OnPropertyChanged("SubFunctionItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<FunctionItemDTO> _SubFunctionItems = new global::System.Data.Services.Client.DataServiceCollection<FunctionItemDTO>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ComplexType UniCloud.Application.BaseManagementBC.DTO.RoleFunctionDTO 的注释。
    /// </summary>
    public partial class RoleFunctionDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 RoleFunctionDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="functionItemId">FunctionItemId 的初始值。</param>
        /// <param name="roleId">RoleId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RoleFunctionDTO CreateRoleFunctionDTO(int ID, int functionItemId, int roleId)
        {
            RoleFunctionDTO roleFunctionDTO = new RoleFunctionDTO();
            roleFunctionDTO.Id = ID;
            roleFunctionDTO.FunctionItemId = functionItemId;
            roleFunctionDTO.RoleId = roleId;
            return roleFunctionDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 FunctionItemId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int FunctionItemId
        {
            get
            {
                return this._FunctionItemId;
            }
            set
            {
                this.OnFunctionItemIdChanging(value);
                this._FunctionItemId = value;
                this.OnFunctionItemIdChanged();
                this.OnPropertyChanged("FunctionItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _FunctionItemId;
        partial void OnFunctionItemIdChanging(int value);
        partial void OnFunctionItemIdChanged();
        /// <summary>
        /// 架构中不存在属性 RoleId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this.OnRoleIdChanging(value);
                this._RoleId = value;
                this.OnRoleIdChanged();
                this.OnPropertyChanged("RoleId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RoleId;
        partial void OnRoleIdChanging(int value);
        partial void OnRoleIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.RoleDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Roles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RoleDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 RoleDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="createDate">CreateDate 的初始值。</param>
        /// <param name="roleFunctions">RoleFunctions 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RoleDTO CreateRoleDTO(int ID, global::System.DateTime createDate, global::System.Collections.ObjectModel.ObservableCollection<RoleFunctionDTO> roleFunctions)
        {
            RoleDTO roleDTO = new RoleDTO();
            roleDTO.Id = ID;
            roleDTO.CreateDate = createDate;
            if ((roleFunctions == null))
            {
                throw new global::System.ArgumentNullException("roleFunctions");
            }
            roleDTO.RoleFunctions = roleFunctions;
            return roleDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 CreateDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
                this.OnPropertyChanged("CreateDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// 架构中不存在属性 RoleFunctions 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<RoleFunctionDTO> RoleFunctions
        {
            get
            {
                return this._RoleFunctions;
            }
            set
            {
                this.OnRoleFunctionsChanging(value);
                this._RoleFunctions = value;
                this.OnRoleFunctionsChanged();
                this.OnPropertyChanged("RoleFunctions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<RoleFunctionDTO> _RoleFunctions = new global::System.Collections.ObjectModel.ObservableCollection<RoleFunctionDTO>();
        partial void OnRoleFunctionsChanging(global::System.Collections.ObjectModel.ObservableCollection<RoleFunctionDTO> value);
        partial void OnRoleFunctionsChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.BusinessLicenseDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BusinessLicenses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class BusinessLicenseDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 BusinessLicenseDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="issuedDate">IssuedDate 的初始值。</param>
        /// <param name="validMonths">ValidMonths 的初始值。</param>
        /// <param name="expireDate">ExpireDate 的初始值。</param>
        /// <param name="state">State 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BusinessLicenseDTO CreateBusinessLicenseDTO(int ID, global::System.DateTime issuedDate, int validMonths, global::System.DateTime expireDate, int state)
        {
            BusinessLicenseDTO businessLicenseDTO = new BusinessLicenseDTO();
            businessLicenseDTO.Id = ID;
            businessLicenseDTO.IssuedDate = issuedDate;
            businessLicenseDTO.ValidMonths = validMonths;
            businessLicenseDTO.ExpireDate = expireDate;
            businessLicenseDTO.State = state;
            return businessLicenseDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 IssuedUnit 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IssuedUnit
        {
            get
            {
                return this._IssuedUnit;
            }
            set
            {
                this.OnIssuedUnitChanging(value);
                this._IssuedUnit = value;
                this.OnIssuedUnitChanged();
                this.OnPropertyChanged("IssuedUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IssuedUnit;
        partial void OnIssuedUnitChanging(string value);
        partial void OnIssuedUnitChanged();
        /// <summary>
        /// 架构中不存在属性 IssuedDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime IssuedDate
        {
            get
            {
                return this._IssuedDate;
            }
            set
            {
                this.OnIssuedDateChanging(value);
                this._IssuedDate = value;
                this.OnIssuedDateChanged();
                this.OnPropertyChanged("IssuedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _IssuedDate;
        partial void OnIssuedDateChanging(global::System.DateTime value);
        partial void OnIssuedDateChanged();
        /// <summary>
        /// 架构中不存在属性 ValidMonths 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ValidMonths
        {
            get
            {
                return this._ValidMonths;
            }
            set
            {
                this.OnValidMonthsChanging(value);
                this._ValidMonths = value;
                this.OnValidMonthsChanged();
                this.OnPropertyChanged("ValidMonths");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ValidMonths;
        partial void OnValidMonthsChanging(int value);
        partial void OnValidMonthsChanged();
        /// <summary>
        /// 架构中不存在属性 ExpireDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ExpireDate
        {
            get
            {
                return this._ExpireDate;
            }
            set
            {
                this.OnExpireDateChanging(value);
                this._ExpireDate = value;
                this.OnExpireDateChanged();
                this.OnPropertyChanged("ExpireDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ExpireDate;
        partial void OnExpireDateChanging(global::System.DateTime value);
        partial void OnExpireDateChanged();
        /// <summary>
        /// 架构中不存在属性 State 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _State;
        partial void OnStateChanging(int value);
        partial void OnStateChanged();
        /// <summary>
        /// 架构中不存在属性 FileContent 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] FileContent
        {
            get
            {
                if ((this._FileContent != null))
                {
                    return ((byte[])(this._FileContent.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnFileContentChanging(value);
                this._FileContent = value;
                this.OnFileContentChanged();
                this.OnPropertyChanged("FileContent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _FileContent;
        partial void OnFileContentChanging(byte[] value);
        partial void OnFileContentChanged();
        /// <summary>
        /// 架构中不存在属性 FileName 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this._FileName = value;
                this.OnFileNameChanged();
                this.OnPropertyChanged("FileName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.AircraftCabinTypeDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AircraftCabinTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AircraftCabinTypeDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AircraftCabinTypeDTO 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AircraftCabinTypeDTO CreateAircraftCabinTypeDTO(int ID)
        {
            AircraftCabinTypeDTO aircraftCabinTypeDTO = new AircraftCabinTypeDTO();
            aircraftCabinTypeDTO.Id = ID;
            return aircraftCabinTypeDTO;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Note 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 UniCloud.Application.BaseManagementBC.DTO.XmlSettingDTO 的注释。
    /// </summary>
    /// <KeyProperties>
    /// XmlSettingId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("XmlSettings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("XmlSettingId")]
    public partial class XmlSettingDTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 XmlSettingDTO 对象。
        /// </summary>
        /// <param name="xmlSettingId">XmlSettingId 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static XmlSettingDTO CreateXmlSettingDTO(global::System.Guid xmlSettingId)
        {
            XmlSettingDTO xmlSettingDTO = new XmlSettingDTO();
            xmlSettingDTO.XmlSettingId = xmlSettingId;
            return xmlSettingDTO;
        }
        /// <summary>
        /// 架构中不存在属性 XmlSettingId 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid XmlSettingId
        {
            get
            {
                return this._XmlSettingId;
            }
            set
            {
                this.OnXmlSettingIdChanging(value);
                this._XmlSettingId = value;
                this.OnXmlSettingIdChanged();
                this.OnPropertyChanged("XmlSettingId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _XmlSettingId;
        partial void OnXmlSettingIdChanging(global::System.Guid value);
        partial void OnXmlSettingIdChanged();
        /// <summary>
        /// 架构中不存在属性 SettingType 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SettingType
        {
            get
            {
                return this._SettingType;
            }
            set
            {
                this.OnSettingTypeChanging(value);
                this._SettingType = value;
                this.OnSettingTypeChanged();
                this.OnPropertyChanged("SettingType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SettingType;
        partial void OnSettingTypeChanging(string value);
        partial void OnSettingTypeChanged();
        /// <summary>
        /// 架构中不存在属性 SettingContent 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SettingContent
        {
            get
            {
                return this._SettingContent;
            }
            set
            {
                this.OnSettingContentChanging(value);
                this._SettingContent = value;
                this.OnSettingContentChanged();
                this.OnPropertyChanged("SettingContent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SettingContent;
        partial void OnSettingContentChanging(string value);
        partial void OnSettingContentChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
