//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.UserDataService.FoundLdapGroupInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://172.18.8.168:10000/SINGPOINT/services/FoundLdapGroupInfo", ConfigurationName="FoundLdapGroupInfo.FoundLdapGroupInfo")]
    public interface FoundLdapGroupInfo {
        
        // CODEGEN: 消息 foundLdapGroupRequest 的包装命名空间(http://singlepoint.soa.com)以后生成的消息协定与默认值(http://172.18.8.168:10000/SINGPOINT/services/FoundLdapGroupInfo)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupResponse foundLdapGroup(UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupResponse> foundLdapGroupAsync(UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="foundLdapGroup", WrapperNamespace="http://singlepoint.soa.com", IsWrapped=true)]
    public partial class foundLdapGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ldapHost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ldapPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string adminAcnt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string adminPwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string orgNo;
        
        public foundLdapGroupRequest() {
        }
        
        public foundLdapGroupRequest(string ldapHost, string ldapPort, string adminAcnt, string adminPwd, string orgNo) {
            this.ldapHost = ldapHost;
            this.ldapPort = ldapPort;
            this.adminAcnt = adminAcnt;
            this.adminPwd = adminPwd;
            this.orgNo = orgNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="foundLdapGroupResponse", WrapperNamespace="http://172.18.8.168:10000/SINGPOINT/services/FoundLdapGroupInfo", IsWrapped=true)]
    public partial class foundLdapGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string foundLdapGroupReturn;
        
        public foundLdapGroupResponse() {
        }
        
        public foundLdapGroupResponse(string foundLdapGroupReturn) {
            this.foundLdapGroupReturn = foundLdapGroupReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FoundLdapGroupInfoChannel : UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoundLdapGroupInfoClient : System.ServiceModel.ClientBase<UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo>, UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo {
        
        public FoundLdapGroupInfoClient() {
        }
        
        public FoundLdapGroupInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoundLdapGroupInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoundLdapGroupInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoundLdapGroupInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupResponse UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo.foundLdapGroup(UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest request) {
            return base.Channel.foundLdapGroup(request);
        }
        
        public string foundLdapGroup(string ldapHost, string ldapPort, string adminAcnt, string adminPwd, string orgNo) {
            UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest inValue = new UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest();
            inValue.ldapHost = ldapHost;
            inValue.ldapPort = ldapPort;
            inValue.adminAcnt = adminAcnt;
            inValue.adminPwd = adminPwd;
            inValue.orgNo = orgNo;
            UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupResponse retVal = ((UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo)(this)).foundLdapGroup(inValue);
            return retVal.foundLdapGroupReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupResponse> UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo.foundLdapGroupAsync(UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest request) {
            return base.Channel.foundLdapGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupResponse> foundLdapGroupAsync(string ldapHost, string ldapPort, string adminAcnt, string adminPwd, string orgNo) {
            UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest inValue = new UniCloud.UserDataService.FoundLdapGroupInfo.foundLdapGroupRequest();
            inValue.ldapHost = ldapHost;
            inValue.ldapPort = ldapPort;
            inValue.adminAcnt = adminAcnt;
            inValue.adminPwd = adminPwd;
            inValue.orgNo = orgNo;
            return ((UniCloud.UserDataService.FoundLdapGroupInfo.FoundLdapGroupInfo)(this)).foundLdapGroupAsync(inValue);
        }
    }
}
