//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.UserDataService.FoundLdapUserInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://172.18.8.168:10000/SINGPOINT/services/FoundLdapUserInfo", ConfigurationName="FoundLdapUserInfo.FoundLdapUserInfo")]
    public interface FoundLdapUserInfo {
        
        // CODEGEN: 消息 foundLdapUsersRequest 的包装命名空间(http://singlepoint.soa.com)以后生成的消息协定与默认值(http://172.18.8.168:10000/SINGPOINT/services/FoundLdapUserInfo)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersResponse foundLdapUsers(UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersResponse> foundLdapUsersAsync(UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="foundLdapUsers", WrapperNamespace="http://singlepoint.soa.com", IsWrapped=true)]
    public partial class foundLdapUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ldapHost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ldapPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string adminAcnt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string adminPwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string orgNo;
        
        public foundLdapUsersRequest() {
        }
        
        public foundLdapUsersRequest(string ldapHost, string ldapPort, string adminAcnt, string adminPwd, string orgNo) {
            this.ldapHost = ldapHost;
            this.ldapPort = ldapPort;
            this.adminAcnt = adminAcnt;
            this.adminPwd = adminPwd;
            this.orgNo = orgNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="foundLdapUsersResponse", WrapperNamespace="http://172.18.8.168:10000/SINGPOINT/services/FoundLdapUserInfo", IsWrapped=true)]
    public partial class foundLdapUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string foundLdapUsersReturn;
        
        public foundLdapUsersResponse() {
        }
        
        public foundLdapUsersResponse(string foundLdapUsersReturn) {
            this.foundLdapUsersReturn = foundLdapUsersReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FoundLdapUserInfoChannel : UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoundLdapUserInfoClient : System.ServiceModel.ClientBase<UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo>, UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo {
        
        public FoundLdapUserInfoClient() {
        }
        
        public FoundLdapUserInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoundLdapUserInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoundLdapUserInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoundLdapUserInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersResponse UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo.foundLdapUsers(UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest request) {
            return base.Channel.foundLdapUsers(request);
        }
        
        public string foundLdapUsers(string ldapHost, string ldapPort, string adminAcnt, string adminPwd, string orgNo) {
            UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest inValue = new UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest();
            inValue.ldapHost = ldapHost;
            inValue.ldapPort = ldapPort;
            inValue.adminAcnt = adminAcnt;
            inValue.adminPwd = adminPwd;
            inValue.orgNo = orgNo;
            UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersResponse retVal = ((UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo)(this)).foundLdapUsers(inValue);
            return retVal.foundLdapUsersReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersResponse> UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo.foundLdapUsersAsync(UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest request) {
            return base.Channel.foundLdapUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersResponse> foundLdapUsersAsync(string ldapHost, string ldapPort, string adminAcnt, string adminPwd, string orgNo) {
            UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest inValue = new UniCloud.UserDataService.FoundLdapUserInfo.foundLdapUsersRequest();
            inValue.ldapHost = ldapHost;
            inValue.ldapPort = ldapPort;
            inValue.adminAcnt = adminAcnt;
            inValue.adminPwd = adminPwd;
            inValue.orgNo = orgNo;
            return ((UniCloud.UserDataService.FoundLdapUserInfo.FoundLdapUserInfo)(this)).foundLdapUsersAsync(inValue);
        }
    }
}
