//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniCloud.Presentation.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniCloud.Presentation.Localization.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全天 的本地化字符串。
        /// </summary>
        public static string AllDayEvent {
            get {
                return ResourceManager.GetString("AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日程项 的本地化字符串。
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日程循环 的本地化字符串。
        /// </summary>
        public static string AppointmentRecurrence {
            get {
                return ResourceManager.GetString("AppointmentRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日程时间 的本地化字符串。
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动隐藏 的本地化字符串。
        /// </summary>
        public static string Auto_hide {
            get {
                return ResourceManager.GetString("Auto_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要内容 的本地化字符串。
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级 的本地化字符串。
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度 的本地化字符串。
        /// </summary>
        public static string Categorize {
            get {
                return ResourceManager.GetString("Categorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日程 的本地化字符串。
        /// </summary>
        public static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按天 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日程 的本地化字符串。
        /// </summary>
        public static string DeleteAppointment {
            get {
                return ResourceManager.GetString("DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日程项 的本地化字符串。
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除这个日程项？ 的本地化字符串。
        /// </summary>
        public static string DeleteItemQuestion {
            get {
                return ResourceManager.GetString("DeleteItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteOccurrence {
            get {
                return ResourceManager.GetString("DeleteOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串2 的本地化字符串。
        /// </summary>
        public static string DeleteRecurringItem {
            get {
                return ResourceManager.GetString("DeleteRecurringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串3 的本地化字符串。
        /// </summary>
        public static string DeleteRecurringItemQueDeleteRecurringItemQuestion {
            get {
                return ResourceManager.GetString("DeleteRecurringItemQueDeleteRecurringItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除序列 的本地化字符串。
        /// </summary>
        public static string DeleteSeries {
            get {
                return ResourceManager.GetString("DeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠 的本地化字符串。
        /// </summary>
        public static string Dockable {
            get {
                return ResourceManager.GetString("Dockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串4 的本地化字符串。
        /// </summary>
        public static string DragRecurringWarning {
            get {
                return ResourceManager.GetString("DragRecurringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串5 的本地化字符串。
        /// </summary>
        public static string DurationColon {
            get {
                return ResourceManager.GetString("DurationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationDay {
            get {
                return ResourceManager.GetString("DurationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationDays {
            get {
                return ResourceManager.GetString("DurationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationHour {
            get {
                return ResourceManager.GetString("DurationHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationHours {
            get {
                return ResourceManager.GetString("DurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationMinute {
            get {
                return ResourceManager.GetString("DurationMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationWeek {
            get {
                return ResourceManager.GetString("DurationWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周（间隔） 的本地化字符串。
        /// </summary>
        public static string DurationWeeks {
            get {
                return ResourceManager.GetString("DurationWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑日程 的本地化字符串。
        /// </summary>
        public static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑上级日程 的本地化字符串。
        /// </summary>
        public static string EditParentAppointment {
            get {
                return ResourceManager.GetString("EditParentAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string EditRecurrence {
            get {
                return ResourceManager.GetString("EditRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串6 的本地化字符串。
        /// </summary>
        public static string EditRecurrenceCommandText {
            get {
                return ResourceManager.GetString("EditRecurrenceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串7 的本地化字符串。
        /// </summary>
        public static string EditRecurrenceRule {
            get {
                return ResourceManager.GetString("EditRecurrenceRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束于 的本地化字符串。
        /// </summary>
        public static string EndAfter {
            get {
                return ResourceManager.GetString("EndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截止日期 的本地化字符串。
        /// </summary>
        public static string EndBy {
            get {
                return ResourceManager.GetString("EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string EndColon {
            get {
                return ResourceManager.GetString("EndColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串9 的本地化字符串。
        /// </summary>
        public static string EndDateBeforeStart {
            get {
                return ResourceManager.GetString("EndDateBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每 的本地化字符串。
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个工作日 的本地化字符串。
        /// </summary>
        public static string EveryWeekday {
            get {
                return ResourceManager.GetString("EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一周 的本地化字符串。
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浮动 的本地化字符串。
        /// </summary>
        public static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第四周 的本地化字符串。
        /// </summary>
        public static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低级 的本地化字符串。
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击添加新项 的本地化字符串。
        /// </summary>
        public static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除筛选 的本地化字符串。
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和 的本地化字符串。
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包括 的本地化字符串。
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包括 的本地化字符串。
        /// </summary>
        public static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含在 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含在 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNotContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始于 的本地化字符串。
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖拽列标题到此，以根据该列分组 的本地化字符串。
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组标题 的本地化字符串。
        /// </summary>
        public static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组依据： 的本地化字符串。
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级别 的本地化字符串。
        /// </summary>
        public static string HighImportance {
            get {
                return ResourceManager.GetString("HighImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串12 的本地化字符串。
        /// </summary>
        public static string InvalidRecurrenceRuleMessage {
            get {
                return ResourceManager.GetString("InvalidRecurrenceRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串13 的本地化字符串。
        /// </summary>
        public static string InvalidRecurrenceRuleTitle {
            get {
                return ResourceManager.GetString("InvalidRecurrenceRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一周 的本地化字符串。
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低级别 的本地化字符串。
        /// </summary>
        public static string LowImportance {
            get {
                return ResourceManager.GetString("LowImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按月 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每月 的本地化字符串。
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无结束日期 的本地化字符串。
        /// </summary>
        public static string NoEndDate {
            get {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个循环 的本地化字符串。
        /// </summary>
        public static string Occurrences {
            get {
                return ResourceManager.GetString("Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 于 的本地化字符串。
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /每 的本地化字符串。
        /// </summary>
        public static string OfEvery {
            get {
                return ResourceManager.GetString("OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开单个日程项 的本地化字符串。
        /// </summary>
        public static string OpenOccurrence {
            get {
                return ResourceManager.GetString("OpenOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日程项 的本地化字符串。
        /// </summary>
        public static string OpenRecurringItem {
            get {
                return ResourceManager.GetString("OpenRecurringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日程项？ 的本地化字符串。
        /// </summary>
        public static string OpenRecurringItemQuestion {
            get {
                return ResourceManager.GetString("OpenRecurringItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日程序列 的本地化字符串。
        /// </summary>
        public static string OpenSeries {
            get {
                return ResourceManager.GetString("OpenSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加急 的本地化字符串。
        /// </summary>
        public static string OutOfOffice {
            get {
                return ResourceManager.GetString("OutOfOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页，共 的本地化字符串。
        /// </summary>
        public static string RadDataPagerOf {
            get {
                return ResourceManager.GetString("RadDataPagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        public static string RadDataPagerPage {
            get {
                return ResourceManager.GetString("RadDataPagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环时段 的本地化字符串。
        /// </summary>
        public static string RangeOfRecurrence {
            get {
                return ResourceManager.GetString("RangeOfRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环：每 的本地化字符串。
        /// </summary>
        public static string RecurEvery {
            get {
                return ResourceManager.GetString("RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环模式 的本地化字符串。
        /// </summary>
        public static string RecurrencePattern {
            get {
                return ResourceManager.GetString("RecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除循环 的本地化字符串。
        /// </summary>
        public static string RemoveRecurrence {
            get {
                return ResourceManager.GetString("RemoveRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并关闭 的本地化字符串。
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string SaveAndCloseCommandText {
            get {
                return ResourceManager.GetString("SaveAndCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存日程 的本地化字符串。
        /// </summary>
        public static string SaveAppointment {
            get {
                return ResourceManager.GetString("SaveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串21 的本地化字符串。
        /// </summary>
        public static string SaveRecurrence {
            get {
                return ResourceManager.GetString("SaveRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二周 的本地化字符串。
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串22 的本地化字符串。
        /// </summary>
        public static string SetDayViewMode {
            get {
                return ResourceManager.GetString("SetDayViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串23 的本地化字符串。
        /// </summary>
        public static string SetMonthViewMode {
            get {
                return ResourceManager.GetString("SetMonthViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串24 的本地化字符串。
        /// </summary>
        public static string SetTimelineViewMode {
            get {
                return ResourceManager.GetString("SetTimelineViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串25 的本地化字符串。
        /// </summary>
        public static string SetWeekViewMode {
            get {
                return ResourceManager.GetString("SetWeekViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展示 的本地化字符串。
        /// </summary>
        public static string ShowAs {
            get {
                return ResourceManager.GetString("ShowAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string StartColon {
            get {
                return ResourceManager.GetString("StartColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以选项卡式文档停靠 的本地化字符串。
        /// </summary>
        public static string Tabbed_document {
            get {
                return ResourceManager.GetString("Tabbed_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中级 的本地化字符串。
        /// </summary>
        public static string Tentative {
            get {
                return ResourceManager.GetString("Tentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三周 的本地化字符串。
        /// </summary>
        public static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间轴 的本地化字符串。
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重要级别 的本地化字符串。
        /// </summary>
        public static string TimeMarkers {
            get {
                return ResourceManager.GetString("TimeMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无题 的本地化字符串。
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按周 的本地化字符串。
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作日 的本地化字符串。
        /// </summary>
        public static string WeekDays {
            get {
                return ResourceManager.GetString("WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周末 的本地化字符串。
        /// </summary>
        public static string WeekendDays {
            get {
                return ResourceManager.GetString("WeekendDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每周 的本地化字符串。
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        public static string WeeksOn {
            get {
                return ResourceManager.GetString("WeeksOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每年 的本地化字符串。
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
